### ISSUE TITLE
ValueError: probabilities do not sum to 1

### ISSUE THREAD

**Issue by philross** [PennyLaneAI/pennylane-lightning-gpu#3]
-------------------------------------------------------------------------------------------------------------

#### Issue description

I am trying to run QAOA using the lightning.gpu simulator, but I am getting an error in the step_and_cost function. Other simulator such as qulacs.simulator are working fine, so I guess it has something to do with the lightning.gpu simulator.

* *Actual behavior:* `optimizer.step_and_cost(cost_function, params)` fails with "probabilities do not sum to 1" when using the lightning.gpu simulator.

* *Reproduces how often:* 100%

* *System information:* 
```
>>> import pennylane as qml; qml.about()
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Name: PennyLane
Version: 0.22.1
Summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
Home-page: https://github.com/XanaduAI/pennylane
Author: 
Author-email: 
License: Apache License 2.0
Location: /home/user/anaconda3/envs/myenv/lib/python3.9/site-packages
Requires: retworkx, networkx, toml, autoray, cachetools, appdirs, autograd, pennylane-lightning, numpy, scipy, semantic-version
Required-by: pennylane-qulacs, PennyLane-Lightning, PennyLane-Lightning-GPU, amazon-braket-pennylane-plugin
Platform info:           Linux-5.4.0-100-generic-x86_64-with-glibc2.31
Python version:          3.9.7
Numpy version:           1.20.3
Scipy version:           1.7.3
Installed devices:
- braket.aws.qubit (amazon-braket-pennylane-plugin-1.5.2)
- braket.local.qubit (amazon-braket-pennylane-plugin-1.5.2)
- default.gaussian (PennyLane-0.22.1)
- default.mixed (PennyLane-0.22.1)
- default.qubit (PennyLane-0.22.1)
- default.qubit.autograd (PennyLane-0.22.1)
- default.qubit.jax (PennyLane-0.22.1)
- default.qubit.tf (PennyLane-0.22.1)
- default.qubit.torch (PennyLane-0.22.1)
- lightning.qubit (PennyLane-Lightning-0.22.0)
- qulacs.simulator (pennylane-qulacs-0.16.0)
- lightning.gpu (PennyLane-Lightning-GPU-0.1.0)
```
#### Source code and tracebacks

Here is a trace of the error:

```
Traceback (most recent call last):
  File "/home/user/dev/tmp/pycharm_project_70/src/solvers/PennylaneQAOA.py", line 273, in run
    params, cost_before = optimizer.step_and_cost(cost_function, params)
  File "/home/user/anaconda3/envs/myenv/lib/python3.9/site-packages/pennylane/optimize/gradient_descent.py", line 100, in step_and_cost
    g, forward = self.compute_grad(objective_fn, args, kwargs, grad_fn=grad_fn)
  File "/home/user/anaconda3/envs/myenv/lib/python3.9/site-packages/pennylane/optimize/gradient_descent.py", line 158, in compute_grad
    grad = g(*args, **kwargs)
  File "/home/user/anaconda3/envs/myenv/lib/python3.9/site-packages/pennylane/_grad.py", line 113, in __call__
    grad_value, ans = grad_fn(*args, **kwargs)
  File "/home/user/anaconda3/envs/myenv/lib/python3.9/site-packages/autograd/wrap_util.py", line 20, in nary_f
    return unary_operator(unary_f, x, *nary_op_args, **nary_op_kwargs)
  File "/home/user/anaconda3/envs/myenv/lib/python3.9/site-packages/pennylane/_grad.py", line 131, in _grad_with_forward
    vjp, ans = _make_vjp(fun, x)
  File "/home/user/anaconda3/envs/myenv/lib/python3.9/site-packages/autograd/core.py", line 10, in make_vjp
    end_value, end_node =  trace(start_node, fun, x)
  File "/home/user/anaconda3/envs/myenv/lib/python3.9/site-packages/autograd/tracer.py", line 10, in trace
    end_box = fun(start_box)
  File "/home/user/anaconda3/envs/myenv/lib/python3.9/site-packages/autograd/wrap_util.py", line 15, in unary_f
    return fun(*subargs, **kwargs)
  File "/home/user/anaconda3/envs/myenv/lib/python3.9/site-packages/pennylane/vqe/vqe.py", line 206, in __call__
    return self.cost_fn(*args, **kwargs)
  File "/home/user/anaconda3/envs/myenv/lib/python3.9/site-packages/pennylane/vqe/vqe.py", line 196, in cost_fn
    res = circuit(*qnode_args, obs=o, **qnode_kwargs)
  File "/home/user/anaconda3/envs/myenv/lib/python3.9/site-packages/pennylane/qnode.py", line 578, in __call__
    res = qml.execute(
  File "/home/user/anaconda3/envs/myenv/lib/python3.9/site-packages/pennylane/interfaces/batch/__init__.py", line 412, in execute
    res = _execute(
  File "/home/user/anaconda3/envs/myenv/lib/python3.9/site-packages/pennylane/interfaces/batch/autograd.py", line 64, in execute
    return _execute(
  File "/home/user/anaconda3/envs/myenv/lib/python3.9/site-packages/autograd/tracer.py", line 44, in f_wrapped
    ans = f_wrapped(*argvals, **kwargs)
  File "/home/user/anaconda3/envs/myenv/lib/python3.9/site-packages/autograd/tracer.py", line 48, in f_wrapped
    return f_raw(*args, **kwargs)
  File "/home/user/anaconda3/envs/myenv/lib/python3.9/site-packages/pennylane/interfaces/batch/autograd.py", line 108, in _execute
    res, jacs = execute_fn(tapes, **gradient_kwargs)
  File "/home/user/anaconda3/envs/myenv/lib/python3.9/site-packages/pennylane/interfaces/batch/__init__.py", line 173, in wrapper
    res = fn(execution_tapes.values(), **kwargs)
  File "/home/user/anaconda3/envs/myenv/lib/python3.9/site-packages/pennylane/interfaces/batch/__init__.py", line 125, in fn
    return original_fn(tapes, **kwargs)
  File "/home/user/anaconda3/envs/myenv/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/home/user/anaconda3/envs/myenv/lib/python3.9/site-packages/pennylane/_qubit_device.py", line 289, in batch_execute
    res = self.execute(circuit)
  File "/home/user/anaconda3/envs/myenv/lib/python3.9/site-packages/pennylane/_qubit_device.py", line 205, in execute
    self._samples = self.generate_samples()
  File "/home/user/anaconda3/envs/myenv/lib/python3.9/site-packages/pennylane/_qubit_device.py", line 486, in generate_samples
    samples = self.sample_basis_states(number_of_states, rotated_prob)
  File "/home/user/anaconda3/envs/myenv/lib/python3.9/site-packages/pennylane/_qubit_device.py", line 512, in sample_basis_states
    return np.random.choice(basis_states, shots, p=state_probability)
  File "mtrand.pyx", line 933, in numpy.random.mtrand.RandomState.choice
ValueError: probabilities do not sum to 1
```

#### Additional information

The `params` numpy array is of type float64.

**Comment by mlxd** [comment]
Hi @philross thanks for reporting this.
Do you have a minimum reproducible example script/workflow we can use to identify the cause of this?

**Comment by philross** [comment]
Hi @mlxd thanks for the swift reply.
I found the issue:
I was specifying the number of shots when creating the device:
```
dev = qml.device("lightning.gpu", wires=wires, shots=1000)
```
After removing it the error is gone:
```
dev = qml.device("lightning.gpu", wires=wires)
```

So I guess this issue can be closed.

**Comment by mlxd** [comment]
Thanks @philross
